"""
download_data.py -- Download and organize the 140K Real-and-Fake-Faces dataset.

Dataset: https://www.kaggle.com/datasets/xhlulu/140k-real-and-fake-faces
Contains:
  - 70K real face photographs (from Flickr-Faces-HQ)
  - 70K fake faces generated by StyleGAN

After download, organizes into:
  data/processed/train/real/  (50K)
  data/processed/train/fake/  (50K)  
  data/processed/valid/real/  (10K)
  data/processed/valid/fake/  (10K)
  data/processed/test/real/   (10K)
  data/processed/test/fake/   (10K)

Usage:
    python download_data.py
"""

import os
import sys
import shutil
import subprocess
from pathlib import Path

# -- Configuration ------------------------------------------------------------

DATASET_SLUG = "xhlulu/140k-real-and-fake-faces"
DATA_ROOT = Path("data")
RAW_DIR = DATA_ROOT / "raw"
PROCESSED_DIR = DATA_ROOT / "processed"

# Target structure
SPLITS = ["train", "valid", "test"]
CLASSES = ["real", "fake"]


def install_package(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])


def check_kaggle_setup():
    """Checks if kaggle is installed and configured."""
    kaggle_dir = Path.home() / ".kaggle"
    kaggle_json = kaggle_dir / "kaggle.json"
    local_kaggle_json = Path("kaggle.json")

    if not kaggle_json.exists():
        if local_kaggle_json.exists():
            print(f"Found kaggle.json in current directory. Moving to {kaggle_dir}...")
            kaggle_dir.mkdir(parents=True, exist_ok=True)
            shutil.move(str(local_kaggle_json), str(kaggle_json))
        else:
            print(f"\n[WARNING] kaggle.json not found.")
            print(f"  Expected at: {kaggle_json}")
            print(f"  Or in current directory: {local_kaggle_json}")
            print(f"\n  To fix:")
            print(f"    1. Go to https://www.kaggle.com/settings")
            print(f"    2. Scroll to 'API' → Click 'Create New Token'")
            print(f"    3. Place the downloaded kaggle.json in {kaggle_dir}")

    try:
        import kaggle
    except ImportError:
        print("Kaggle library not found. Installing...")
        install_package("kaggle")
        print("Kaggle library installed.")
    except Exception as e:
        print(f"[WARN] Error importing kaggle: {e}")


def download_dataset():
    """Downloads the dataset using Kaggle CLI."""
    print(f"\n{'=' * 60}")
    print(f"  Downloading: {DATASET_SLUG}")
    print(f"  Target: {RAW_DIR}")
    print(f"{'=' * 60}")

    RAW_DIR.mkdir(parents=True, exist_ok=True)

    cmd = f"kaggle datasets download -d {DATASET_SLUG} -p {RAW_DIR} --unzip"
    try:
        subprocess.run(cmd, shell=True, check=True)
        print("\n  [OK] Download complete!")
    except subprocess.CalledProcessError as e:
        print(f"\n[ERROR] Download failed: {e}")
        print("\nTroubleshooting:")
        print("  1. Ensure kaggle.json is properly configured")
        print("  2. Try: pip install --upgrade kaggle")
        print(f"  3. Manual download: https://www.kaggle.com/datasets/{DATASET_SLUG}")
        sys.exit(1)


def organize_dataset():
    """
    Organizes the downloaded data into the expected structure.
    
    The 140k dataset typically extracts to:
      data/raw/real_vs_fake/
        real-vs-fake/
          train/ (real/, fake/)
          valid/ (real/, fake/)
          test/  (real/, fake/)
    
    We copy this into:
      data/processed/train/real/, train/fake/, etc.
    """
    print("\n[2/3] Organizing dataset...")

    # Find the extraction root by looking for 'train' directory
    found_root = None
    
    # Search for the train directory within raw
    for path in RAW_DIR.rglob("train"):
        if path.is_dir() and (path / "real").exists():
            found_root = path.parent
            break

    if not found_root:
        # Maybe the structure is flat: raw/train/real, raw/train/fake
        if (RAW_DIR / "train" / "real").exists():
            found_root = RAW_DIR
        else:
            print("[ERROR] Could not find expected dataset structure.")
            print("  Expected: .../train/real/ and .../train/fake/")
            print(f"  Searched in: {RAW_DIR}")
            print("\n  Contents of raw dir:")
            for p in RAW_DIR.rglob("*"):
                if p.is_dir():
                    print(f"    [DIR] {p.relative_to(RAW_DIR)}")
            return False

    print(f"  Found dataset root: {found_root}")

    # Create processed directory structure
    for split in SPLITS:
        for cls in CLASSES:
            target = PROCESSED_DIR / split / cls
            target.mkdir(parents=True, exist_ok=True)

    # Copy/move files
    total_copied = 0
    for split in SPLITS:
        source_split = found_root / split
        if not source_split.exists():
            print(f"  [WARN] Split not found: {split}")
            continue

        for cls in CLASSES:
            source_cls = source_split / cls
            target_cls = PROCESSED_DIR / split / cls

            if not source_cls.exists():
                print(f"  [WARN] Class not found: {split}/{cls}")
                continue

            files = list(source_cls.glob("*.*"))
            print(f"  Copying {split}/{cls}: {len(files)} files...")

            for f in files:
                dest = target_cls / f.name
                if not dest.exists():
                    shutil.copy2(str(f), str(dest))
                    total_copied += 1

    print(f"\n  [OK] Copied {total_copied} total files")
    return True


def print_summary():
    """Prints dataset statistics."""
    print(f"\n{'=' * 60}")
    print(f"  DATASET SUMMARY")
    print(f"{'=' * 60}")

    total = 0
    for split in SPLITS:
        split_total = 0
        for cls in CLASSES:
            cls_dir = PROCESSED_DIR / split / cls
            if cls_dir.exists():
                count = len(list(cls_dir.glob("*.*")))
                split_total += count
                print(f"  {split:6s}/{cls:4s}: {count:>6,} images")
            else:
                print(f"  {split:6s}/{cls:4s}: not found")
        print(f"  {split:6s} total : {split_total:>6,}")
        total += split_total
        print()

    print(f"  GRAND TOTAL: {total:>6,} images")
    print(f"{'=' * 60}")

    if total > 0:
        print(f"\n  [OK] Dataset ready! Next step:")
        print(f"    python src/train.py")
    else:
        print(f"\n  [FAIL] No images found. Check the download.")


if __name__ == "__main__":
    check_kaggle_setup()
    download_dataset()
    success = organize_dataset()
    if success:
        print_summary()
