import json

with open('extension/model/model.json', 'r') as f:
    data = json.load(f)

print('Format:', data.get('format'))
print('Generated by:', data.get('generatedBy'))
print('Converted by:', data.get('convertedBy'))

if 'signature' in data:
    sig = data['signature']
    print('\n=== Input Signature ===')
    if 'inputs' in sig:
        for name, info in sig['inputs'].items():
            print(f"  {name}: dtype={info.get('dtype')}, shape={info.get('tensorShape')}")
    print('\n=== Output Signature ===')
    if 'outputs' in sig:
        for name, info in sig['outputs'].items():
            print(f"  {name}: dtype={info.get('dtype')}, shape={info.get('tensorShape')}")

if 'userDefinedMetadata' in data:
    print('\n=== User Metadata ===')
    print(json.dumps(data['userDefinedMetadata'], indent=2))

if 'modelTopology' in data:
    topo = data['modelTopology']
    if 'node' in topo:
        print(f"\n=== Graph: {len(topo['node'])} nodes ===")
        # Show first 3 and last 3 nodes
        for n in topo['node'][:3]:
            print(f"  {n.get('name', '?')} ({n.get('op', '?')})")
        print("  ...")
        for n in topo['node'][-3:]:
            print(f"  {n.get('name', '?')} ({n.get('op', '?')})")
